name: Update Cesium ion token
description: Fetches a new Cesium ion token and updates the Google Cloud Secret Manager secret
inputs:
  secret:
    description: Name of the Google Cloud Secret Manager secret
    required: true

runs:
  using: composite
  steps:
    - name: Fetch Cesium ion token
      id: fetch
      shell: bash
      run: |
        ION_TOKEN=$( \
          curl -s https://raw.githubusercontent.com/CesiumGS/cesium/main/packages/engine/Source/Core/Ion.js | \
          node -e " \
            process.stdin.resume(); \
            process.stdin.setEncoding('utf8'); \
            let data = ''; \
            process.stdin.on('data', chunk => { data += chunk; }); \
            process.stdin.on('end', () => { \
              const defaultAccessTokenRegex = /const defaultAccessToken =(\n| ).*\"(.*)\";/; \
              const match = data.match(defaultAccessTokenRegex); \
              console.log(match ? match[2] : 'Token not found'); \
            }); \
          " \
        )

        # Trim leading/trailing whitespace and remove newlines
        CLEAN_TOKEN=$(echo "$ION_TOKEN" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

        echo "token=$CLEAN_TOKEN" >> $GITHUB_OUTPUT

    - name: Update Secret Manager secret
      shell: bash
      run: |
        TOKEN="${{ steps.fetch.outputs.token }}"
        # Remove any leftover whitespace or newlines again, just in case
        CLEANED=$(echo "$TOKEN" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        echo -n "$CLEANED" | gcloud secrets versions add ${{ inputs.secret }} --data-file=-
