name: Stage
description: Merge main branch to release branch

runs:
  using: composite
  steps:
    - name: git config
      shell: bash
      run: |
        git config --global user.name ${{ inputs.gh_app_id  }}
        git config --global user.email ${{ inputs.gh_app_id }}+${{ inputs.gh_app_user }}[bot]@users.noreply.github.com
        git config --global pull.rebase false
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.gh_app_id }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}
    - name: Checkout release branch
      shell: bash
      run: git switch release || git switch -c release
    - name: Merge main branch to release branch
      shell: bash
      run: git merge -X theirs main
    - name: Git push
      shell: bash
      run: git push origin release
