name: Remove Cloud Run Tag
description: Remove tag from Cloud Run service revisions
inputs:
  region:
    description: "The region to deploy the Cloud Run service to"
    required: true
  service:
    description: "The service to deploy"
  service_account:
    description: "The service account to use for authentication"
    required: true
  tag:
    description: "The tag to remove from the Cloud Run service revisions"
    required: true
  workload_identity_provider:
    description: "The workload identity provider to use for authentication"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
      with:
        service_account: ${{ inputs.service_account }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
    - name: Remove revision tags
      shell: bash
      run: |
        gcloud run services update-traffic ${{ inputs.service }} \
          --region ${{ inputs.region }} \
          --remove-tags=${{ inputs.tag }} || echo "Warning: Failed to remove tag ${{ inputs.tag }} - it may not exist"
