name: Release
description: Generate CHANGELOG, commit, and push to release branch

inputs:
  version:
    required: false
    description: A new version ("vX.X.X"), "patch", "minor", "major", "prepatch", "preminor", "premajor", or "prerelease". Default automatically detects a new version from commits.
    default: minor
runs:
  using: composite
  steps:
    - name: Set up git config
      shell: bash
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: changelog
      name: Generate CHANGELOG
      uses: reearth/changelog-action@main
      with:
        version: ${{ github.event.inputs.version }}
        repo: ${{ github.repository }}
        latest: CHANGELOG_latest.md
    - name: Upload latest CHANGELOG
      uses: actions/upload-artifact@v4
      with:
        name: changelog-${{ steps.changelog.outputs.version }}
        path: CHANGELOG_latest.md
    - name: Commit & push to release
      shell: bash
      env:
        TAG: ${{ steps.changelog.outputs.version }}
      run: |
        rm CHANGELOG_latest.md
        git add CHANGELOG.md
        git commit -am "$TAG"
        git tag $TAG
        git push --atomic origin release $TAG
    - name: Commit & push to main
      shell: bash
      run: git switch main && git cherry-pick release && git push
