name: Build Docker Image
description: Build and optionally push a Docker image, outputting its digest.
inputs:
  image:
    type: string
    description: The image to deploy without tags
    required: true
  context:
    type: string
    description: Build context
    required: true
  dockerhub_username:
    description: DockerHub username
    type: string
    required: false
  dockerhub_password:
    description: DockerHub password
    type: string
    required: false
  use_dockerhub:
    description: Whether to push to DockerHub
    required: false
    default: false
  sha_short:
    type: string
    required: false
  new_tag:
    type: string
    required: false
  new_tag_short:
    type: string
    required: false
  name:
    type: string
    required: false
outputs:
  digest:
    description: The digest of the deployed docker image
    value: ${{ steps.build.outputs.digest }}
  image:
    description: The full name of the deployed docker image
    value: '${{ inputs.image }}@${{ steps.build.outputs.digest }}'
runs:
  using: composite
  steps:
    - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: inputs.use_dockerhub == 'true'
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_password }}
      - name: Get options
        shell: bash
        id: options
        env:
          IMAGE_NAME: ${{ inputs.image }}
          TAG: ${{ inputs.new_tag_short }}
          NAME: ${{ inputs.name }}
          SHA: ${{ inputs.sha_short }}
        run: |
          if [[ -n $TAG ]]; then
            VERSION=$TAG
            TAGS=$IMAGE_NAME:$TAG
            if [[ ! $TAG =~ '-' ]]; then
              TAGS+=,${IMAGE_NAME}:${TAG%.*}
              TAGS+=,${IMAGE_NAME}:${TAG%%.*}
              TAGS+=,${IMAGE_NAME}:latest
            fi
          else
            VERSION=$SHA
            TAGS=$IMAGE_NAME:$NAME
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: ${{ inputs.context }}
          push: true
          build-args: |
            GITHUB_SHA=${{ inputs.sha_short }}
            VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
