name: Prepare build
description: Prepare build information
inputs:
  release_branch:
    description: Branch to use for release
    required: false
    default: release
outputs:
  sha_short:
    description: Short SHA of the commit
    value: ${{ jobs.prepare.outputs.sha_short }}
  new_tag:
    description: Tag name of the commit
    value: ${{ jobs.prepare.outputs.new_tag }}
  new_tag_short:
    description: Short tag name of the commit
    value: ${{ jobs.prepare.outputs.new_tag_short }}
  name:
    description: Name of the build (nightly or rc)
    value: ${{ jobs.prepare.outputs.name }}c
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Fetch tags
      shell: bash
      run: git fetch --prune --unshallow --tags
    - name: Get info
      shell: bash
      id: info
      # The tag name should be retrieved lazily, as tagging may be delayed.
      env:
        BRANCH: ${{ github.head_ref || github.ref_name }}
        RELEASE_BRANCH: ${{ inputs.release_branch }}
      run: |
        echo "sha_short=$(git rev-parse --short HEAD))" >> "$GITHUB_OUTPUT"
        if [[ "$BRANCH" = "$RELEASE_BRANCH" ]]; then
          TAG=$(git tag --points-at HEAD)
          if [[ ! -z "$TAG" ]]; then
            echo "new_tag=$TAG" >> "$GITHUB_OUTPUT"
            echo "new_tag_short=${TAG#v}" >> "$GITHUB_OUTPUT"
          else
            echo "name=rc" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "name=nightly" >> "$GITHUB_OUTPUT"
        fi
    - name: Show info
      shell: bash
      env:
        SHA_SHORT: ${{ steps.info.outputs.sha_short }}
        NEW_TAG: ${{ steps.info.outputs.new_tag }}
        NEW_TAG_SHORT: ${{ steps.info.outputs.new_tag_short }}
        NAME: ${{ steps.info.outputs.name }}
      run: echo "sha_short=$SHA_SHORT, new_tag=$NEW_TAG, new_tag_short=$NEW_TAG_SHORT, name=$NAME"
