name: Deploy to Cloud Run with Service Tag
description: Deploy to Cloud Run with Service Tag
inputs:
  image:
    description: "The image to deploy"
    required: true
  image_internal:
    description: "The image stored in GAR"
    required: true
  region:
    description: "The region to deploy the Cloud Run service to"
    required: true
  service:
    description: "The service to deploy"
    required: true
  service_account:
    description: "The service account to use for authentication"
    required: true
  tag:
    description: "The tag to apply to the Cloud Run service revisions"
    required: true
  workload_identity_provider:
    description: "The workload identity provider to use for authentication"
    required: true
outputs:
  url:
    description: "The URL of the deployed Cloud Run service"
    value: ${{ steps.deploy-pr.outputs.url }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
      with:
        service_account: ${{ inputs.service_account }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
    - name: Configure docker
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet
    - name: docker push
      shell: bash
      run: |
        docker pull ${{ inputs.image }}
        docker tag ${{ inputs.image }} ${{ inputs.image_internal }}
        docker push ${{ inputs.image_internal }}
    - name: Deploy to Cloud Run (PR)
      id: deploy-pr
      uses: google-github-actions/deploy-cloudrun@1ec29da1351112c7904fb60454a55e3e1021a51c # v2.7.2
      with:
        service: ${{ inputs.service }}
        skip_default_labels: true
        image: ${{ inputs.image_internal }}
        region: ${{ inputs.region }}
        tag: ${{ inputs.tag }}
        no_traffic: true
    - name: Comment or update PR with preview URL
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const url = `${{ steps.deploy-pr.outputs.url }}`;
          const marker = '<!-- cloud-run-preview -->';
          const body = `${marker}
           🚀 **Cloud Run Preview Deployed**

           🔗 [Click here to open the preview in a new tab](${url})`;

          const { data: comments } = await github.rest.issues.listComments({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const existingComment = comments.find(
            comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes(marker)
          );

          if (existingComment) {
            await github.rest.issues.updateComment({
              comment_id: existingComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
          }
