name: CI
on:
  pull_request:

jobs:
  alex:
    name: Alex
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
      pull-requests: write # To comment to PRs
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: reviewdog/action-alex@b6673b547eeb6d430c87ef02dc3524bdf34e324d # v1.16.1
        with:
          reporter: github-pr-review

  misspell:
    name: Misspell
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
      pull-requests: write # To comment to PRs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1.27.0
        with:
          reporter: github-pr-review
