name: CI
on:
  pull_request:

jobs:
  alex:
    name: Alex
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
      pull-requests: write # To comment to PRs
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review

  misspell:
    name: Misspell
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
      pull-requests: write # To comment to PRs
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
