on:
  workflow_call:
    inputs:
      repo:
        description: Repository name (owner/repo) (prevents execution in different repositories)
        type: string
        required: false
      release_branch:
        type: string
        description: Branch to use for release
        required: false
    outputs:
      sha_short:
        description: "Short SHA of the commit"
        value: ${{ jobs.prepare-build.outputs.sha_short }}
      new_tag:
        description: "Tag name"
        value: ${{ jobs.prepare-build.outputs.new_tag }}
      new_tag_short:
        description: "Short tag name"
        value: ${{ jobs.prepare-build.outputs.new_tag_short }}
      name:
        description: "Build name (e.g. nightly, rc)"
        value: ${{ jobs.prepare-build.outputs.name }}

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == inputs.repo && github.event_name == 'push' && (github.ref_name == 'release' || !startsWith(github.event.head_commit.message, 'v')) }}
    outputs:
      sha_short: ${{ steps.info.outputs.sha_short }}
      new_tag: ${{ steps.info.outputs.new_tag }}
      new_tag_short: ${{ steps.info.outputs.new_tag_short }}
      name: ${{ steps.info.outputs.name }}
    steps:
      - uses: ./actions/prepare-build
        id: info
        with:
          release_branch: ${{ inputs.release_branch }}
