on:
  workflow_call:
    inputs:
      repo:
        description: "Repository to build (e.g. owner/repo)"
        required: true
        type: string
      release_branch:
        type: string
        description: Branch to use for release
        required: false
        default: release

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == inputs.repo && github.event_name == 'push' && (github.ref_name == 'release' || !startsWith(github.event.head_commit.message, 'v')) }}
    outputs:
      sha_short: ${{ steps.info.outputs.sha_short }}
      new_tag: ${{ steps.info.outputs.new_tag }}
      new_tag_short: ${{ steps.info.outputs.new_tag_short }}
      name: ${{ steps.info.outputs.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Fetch tags
        shell: bash
        run: git fetch --prune --unshallow --tags
      - name: Get info
        shell: bash
        id: info
        # The tag name should be retrieved lazily, as tagging may be delayed.
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          RELEASE_BRANCH: ${{ inputs.release_branch }}
        run: |
          echo "sha_short=$(git rev-parse --short HEAD))" >> "$GITHUB_OUTPUT"
          if [[ "$BRANCH" = "$RELEASE_BRANCH" ]]; then
            TAG=$(git tag --points-at HEAD)
            if [[ ! -z "$TAG" ]]; then
              echo "new_tag=$TAG" >> "$GITHUB_OUTPUT"
              echo "new_tag_short=${TAG#v}" >> "$GITHUB_OUTPUT"
            else
              echo "name=rc" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "name=nightly" >> "$GITHUB_OUTPUT"
          fi
      - name: Show info
        shell: bash
        env:
          SHA_SHORT: ${{ steps.info.outputs.sha_short }}
          NEW_TAG: ${{ steps.info.outputs.new_tag }}
          NEW_TAG_SHORT: ${{ steps.info.outputs.new_tag_short }}
          NAME: ${{ steps.info.outputs.name }}
        run: echo "sha_short=$SHA_SHORT, new_tag=$NEW_TAG, new_tag_short=$NEW_TAG_SHORT, name=$NAME"
