name: Validate Nginx Configuration
on:
  workflow_call:
    inputs:
      workdir:
        default: 'web'
        description: 'Default working directory to run the job.'
        required: true
        type: string
      templatedir: # see - https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/entrypoint/20-envsubst-on-templates.sh#L32
        description: 'Nginx configuration template directory. Usually have files with .template extension.'
        required: true
        type: string

jobs:
  validate-nginx-config:
    name: validate-nginx-config
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.WEB_PORT }}
      REAL_IP_HEADER: ${{ vars.WEB_REAL_IP_HEADER }}
      NGINX_ENVSUBST_TEMPLATE_DIR: ${{ inputs.templatedir}}
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - name: check Nginx version
        run: sudo nginx -v
      - name: list Nginx config template directory
        run: ls -l ${{ env.NGINX_ENVSUBST_TEMPLATE_DIR }} /etc/nginx/ /etc/nginx/conf.d/
      - name: download Nginx envsubst script
        run: curl -s -O https://raw.githubusercontent.com/nginxinc/docker-nginx/2879b26c7dedf1d958b1894a5c1b1dec3c026369/entrypoint/20-envsubst-on-templates.sh && chmod +x 20-envsubst-on-templates.sh
      - name: envsubst Nginx config
        run: sudo --preserve-env ./20-envsubst-on-templates.sh
      - name: check generated config files
        run: ls -l /etc/nginx/conf.d/
      - name: test Nginx configuration
        run: sudo nginx -t
